//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovAtelLogReader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("115200")]
        public int ComPortSpeed {
            get {
                return ((int)(this["ComPortSpeed"]));
            }
            set {
                this["ComPortSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Source\\range.txt")]
        public string TextFilePath {
            get {
                return ((string)(this["TextFilePath"]));
            }
            set {
                this["TextFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("amqp://uniframe:uniframe@172.20.12.50:5672/")]
        public string RabbitConnectionString {
            get {
                return ((string)(this["RabbitConnectionString"]));
            }
            set {
                this["RabbitConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ion-node-01")]
        public string KafkaBrokers {
            get {
                return ((string)(this["KafkaBrokers"]));
            }
            set {
                this["KafkaBrokers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public uint PublishRate {
            get {
                return ((uint)(this["PublishRate"]));
            }
            set {
                this["PublishRate"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NovAtelLogReader.Publishers.KafkaPublisher")]
        public string Publisher {
            get {
                return ((string)(this["Publisher"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NovAtelLogReader.Readers.ComPortReader")]
        public string Reader {
            get {
                return ((string)(this["Reader"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NovAtelLogReader.LogRecordFormats.BinaryLogRecordFormat")]
        public string Format {
            get {
                return ((string)(this["Format"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM2")]
        public string ComPortName {
            get {
                return ((string)(this["ComPortName"]));
            }
            set {
                this["ComPortName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>UNLOGALL TRUE</string>
  <string>CNOUPDATE 20HZ</string>
  <string>DIFFCODEBIASCONTROL DISABLE</string>
  <string>EXTERNALCLOCK DISABLE</string>
  <string>RTKDYNAMICS STATIC</string>
  <string>SETIONOTYPE L1L2</string>
  <string>ISMBANDWIDTH 1.0 0.0</string>
  <string>ISMSIGNALCONTROL GPSL2P ENABLE ENABLE</string>
  <string>LOG PSRPOSB ONTIME 1</string>
  <string>LOG RANGEB ONTIME 0.02</string>
  <string>LOG ISMRAWTECB ONNEW</string>
  <string>LOG ISMDETOBSB ONNEW</string>
  <string>LOG ISMREDOBSB ONNEW</string>
  <string>LOG SATXYZ2B ONTIME 10</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection InitCommands {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["InitCommands"]));
            }
            set {
                this["InitCommands"] = value;
            }
        }
    }
}
